Fix #18 dfsTree does not preserve contexts of the original graph
elm-community/graph pull request #30
Opened 2023-06-27 14:19 UTC by Luftzig

Fixes #18 
Solution uses a set of visited nodes instead of removing the currently visited node from the graph.
Root cause: when removing a node from a graph it's incoming and outgoing edges are also removed, modifying the context provided to the visitor function.

2023-09-28 07:47 UTC, sgraf812 requested changes
Sorry to have taken so long to review. Would you like to become (co-)maintainer?

2023-09-28 07:47 UTC, sgraf812 commented on src/Graph.elm
> +                                go seeds1 (Set.insert next visited) acc graph
I don't think this comment is accurate any longer. This code path is only taken when we try to access a node that is not part of the graph.

2023-09-28 07:47 UTC, sgraf812 commented on src/Graph.elm
> +        go seeds visited acc graph =
`graph` is a static argument; it is always `startingGraph`. No need to pass it around, pretending that it will change!

2024-06-11 16:48 UTC, Hofsiedge commented
Closing this due to inactivity in favor of PR #32

2024-06-11 16:48 UTC, closed without merging